In [1]:
# import dataset
import pandas as pd
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# Ignore useless warnings (see SciPy issue #5998)
import warnings
warnings.filterwarnings(action="ignore", message="^internal gelsd")

df = pd.read_excel(r'/home/tuedo/Downloads/ChallengeDataSet-WellsFargo.xlsx') # path to training set
df1 = df.drop('XC', axis=1) # no XC column at first
X = df1.to_numpy()
df2 = df["y"]
y = df2.to_numpy()
# we use numpy arrays instead of dataframes because I'm more comfortable with them

# visualization of training dataset
print(df1)
print(df2)

            X0        X1        X2        X3        X4        X5        X6  \
0     0.985703  0.899527  2.332283  1.044273  1.141718 -1.656647 -1.409265   
1     0.539816  0.243602  1.636048 -0.562150 -0.235560 -1.316039  1.529069   
2    -1.424483 -0.470533  0.095100  0.131981  1.168902 -0.827530 -1.233111   
3    -1.034157 -1.054496  0.339467 -0.829151  0.012123  0.048887  0.573195   
4     0.177091  1.154216  1.004133 -0.724015 -0.508090 -0.478284 -0.524431   
...        ...       ...       ...       ...       ...       ...       ...   
2995  0.127214 -0.644439 -0.356251 -1.188522  0.646979 -1.018895 -0.153524   
2996  0.427700  1.460896 -1.260326  2.206359 -0.981929  0.045186  0.406928   
2997 -0.880540  0.678472  0.493897 -0.118869  0.005285 -0.201233 -0.601732   
2998  0.151291 -0.949928 -1.960683 -1.352557  2.221015 -0.775556  0.932388   
2999  1.351919 -0.353120 -0.918519 -0.417465 -0.688730 -0.157284 -1.233306   

            X7        X8        X9  ...       X21       X22    

In [2]:
from sklearn.linear_model import SGDClassifier
from sklearn.base import clone

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X, y) # initially fit all datapoints, and then we refine within specific classes (A, B, C, D, E)

SGDClassifier(random_state=42)

In [3]:
ind_A = np.where(df["XC"]=='A')
train_A = X[np.ma.masked_array(ind_A[0]), :]
X_A, y_A = train_A[:, 0:30], train_A[:, 30]
clf_A = clone(sgd_clf)
clf_A.fit(X_A, y_A)

ind_B = np.where(df["XC"]=='B')
train_B = X[np.ma.masked_array(ind_B[0]), :]
X_B, y_B = train_B[:, 0:30], train_B[:, 30]
clf_B = clone(sgd_clf)
clf_B.fit(X_B, y_B)

ind_C = np.where(df["XC"]=='C')
train_C = X[np.ma.masked_array(ind_C[0]), :]
X_C, y_C = train_C[:, 0:30], train_C[:, 30]
clf_C = clone(sgd_clf)
clf_C.fit(X_C, y_C)

ind_D = np.where(df["XC"]=='D')
train_D = X[np.ma.masked_array(ind_D[0]), :]
X_D, y_D = train_D[:, 0:30], train_D[:, 30]
clf_D = clone(sgd_clf)
clf_D.fit(X_D, y_D)

ind_E = np.where(df["XC"]=='E')
train_E = X[np.ma.masked_array(ind_E[0]), :]
X_E, y_E = train_E[:, 0:30], train_E[:, 30]
clf_E = clone(sgd_clf)
clf_E.fit(X_E, y_E)

SGDClassifier(random_state=42)

In [4]:
eval_df = pd.read_excel(r'/home/tuedo/Downloads/EvaluationDataSet-WellsFargo.xlsx') # path to eval set
eval_df

X0        X1        X2        X3        X4        X5        X6  \
0    -1.208326  0.184604 -1.360810  0.832539 -1.930396  0.735845 -1.119733   
1     0.350543  0.616101 -0.075601 -1.281581 -1.068448  0.076597  1.575460   
2    -1.053845  1.121272  0.281191  2.062626 -1.873636 -2.093157  0.525051   
3     0.753607 -1.216055  0.901436  0.295607  0.926686 -0.528337 -1.201287   
4    -0.835652 -0.556401 -0.086082  0.020231  0.391678 -0.567884 -0.014241   
...        ...       ...       ...       ...       ...       ...       ...   
6995 -1.668226  0.273806 -0.172127 -1.269599 -0.087146  0.569244  0.136262   
6996 -0.793286  0.831727 -1.176271 -1.471549 -0.650559 -0.365865  0.430448   
6997  0.063172  1.760983 -0.247600 -0.053088  0.325324 -0.436461  0.106183   
6998  0.718720  2.684811 -0.222710 -1.187928 -0.775976 -0.940314  1.352791   
6999  0.874432 -0.203484 -0.612842 -0.143382  0.244501  1.846920  0.430232   

            X7        X8        X9  ...       X22       X23       X24  \
0     0.805059  1.792480  0.231509  ... -0.231612  1.097317 -0.042484   
1     1.419118 -1.170031  0.520044  ...  0.287080 -0.953646 -0.450313   
2     0.461412 -0.564816  0.823737  ... -0.415817  1.278447 -1.707741   
3     0.503883 -0.692658 -0.241763  ...  0.992553 -0.496281 -2.001786   
4     1.297619  0.111214 -0.092910  ... -0.117647 -1.347112  1.290418   
...        ...       ...       ...  ...       ...       ...       ...   
6995  2.294783  0.595258 -0.269437  ... -0.366651 -0.466973 -2.410024   
6996 -0.023555  0.290329 -1.153080  ...  0.059348  1.331673 -2.157887   
6997 -1.662398 -0.310201 -0.383877  ...  0.486854 -0.969630  0.159337   
6998 -1.760964  1.290997 -0.919177  ... -0.747266 -0.443295  0.021663   
6999  0.370525 -0.708310 -1.977424  ...  0.210253 -0.719312 -0.159229   

           X25       X26       X27       X28       X29  XC  scenario  
0     0.910525 -1.018880  0.947496 -0.075102  0.973887   E         1  
1     0.799377  0.639559  1.789031  0.180551  0.114973   D         2  
2    -1.295403 -0.634600 -1.742845 -1.717337 -1.369531   C         3  
3     1.298110  1.138098  2.176901  1.067320  2.481112   A         4  
4     0.501643 -1.753281 -0.608117  1.102466  0.150500   D         5  
...        ...       ...       ...       ...       ...  ..       ...  
6995 -1.076995  0.696290 -0.395424  0.627267  0.209065   B      6996  
6996 -0.264729 -1.279300  2.363626  1.257807  0.688592   E      6997  
6997  0.535240  0.155901 -0.676327 -1.081650 -0.310030   B      6998  
6998 -1.334239 -0.592907 -0.254182 -1.141342  0.633062   E      6999  
6999  1.150589  0.695399  1.506978  1.745755 -1.820189   D      7000  

[7000 rows x 32 columns]

In [5]:
data_eval = eval_df.drop("XC", axis=1).to_numpy()
data_eval.shape

(7000, 31)

In [6]:
X_eval = data_eval[:, 0:30]

In [7]:
# predicting subsets of the test set based on 'XC' column
eval_ind_A = np.where(eval_df["XC"]=='A')
eval_ind_B = np.where(eval_df["XC"]=='B')
eval_ind_C = np.where(eval_df["XC"]=='C')
eval_ind_D = np.where(eval_df["XC"]=='D')
eval_ind_E = np.where(eval_df["XC"]=='E')

eval_A = X_eval[np.ma.masked_array(eval_ind_A[0]), :]
eval_B = X_eval[np.ma.masked_array(eval_ind_B[0]), :]
eval_C = X_eval[np.ma.masked_array(eval_ind_C[0]), :]
eval_D = X_eval[np.ma.masked_array(eval_ind_D[0]), :]
eval_E = X_eval[np.ma.masked_array(eval_ind_E[0]), :]

In [8]:
predict_A = clf_A.predict(eval_A)
predict_B = clf_B.predict(eval_B)
predict_C = clf_C.predict(eval_C)
predict_D = clf_D.predict(eval_D)
predict_E = clf_E.predict(eval_E)
predictions = np.zeros(7000)
predictions

array([0., 0., 0., ..., 0., 0., 0.])

In [9]:
# merging all of our predictions into one array again
ax, bx, cx, dx, ex = 0, 0, 0, 0, 0
i = 0;
for xc in eval_df["XC"]:
    if (xc == "A"):
        predictions[i] = predict_A[ax]
        ax += 1
    elif (xc == "B"):
        predictions[i] = predict_B[bx]
        bx += 1
    elif (xc == "C"):
        predictions[i] = predict_C[cx]
        cx += 1
    elif (xc == "D"):
        predictions[i] = predict_D[dx]
        dx += 1
    elif (xc == "E"):
        predictions[i] = predict_E[ex]
        ex += 1
        
    i += 1

predictions.T

array([1., 0., 1., ..., 0., 0., 0.])

In [10]:
predictions

array([1., 0., 1., ..., 0., 0., 0.])

In [11]:
# recasting into DataFrame

pred_df = pd.DataFrame(data=predictions, columns=["prediction_score"])
pred_df.insert(0, "dataset_id", pd.Series(range(1,7001)), allow_duplicates=False)

In [12]:
pred_df

dataset_id  prediction_score
0              1               1.0
1              2               0.0
2              3               1.0
3              4               0.0
4              5               0.0
...          ...               ...
6995        6996               1.0
6996        6997               0.0
6997        6998               0.0
6998        6999               0.0
6999        7000               0.0

[7000 rows x 2 columns]

In [13]:
# Those are my predictions.
# Tue Do
# August 5, 2020

In [15]:
pred_df.to_excel(r'/home/tuedo/Desktop/predictions.xlsx', index=False) # just so I can export the data